# Generated by Django 5.2.11 on 2026-03-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fraud_flag',
            field=models.BooleanField(default=False, help_text='Marks suspicious payments detected by Payment engine'),
        ),
    ]
