# Generated by Django 5.2.11 on 2026-02-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='Webhook endpoint for payment notifications', null=True),
        ),
    ]
