# Generated by Django 5.2.11 on 2026-02-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_merchant_webhook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='scope',
            field=models.CharField(choices=[('read', 'Read only'), ('write', 'Write access'), ('admin', 'Admin access')], default='admin', help_text='Defines API access level', max_length=10),
        ),
    ]
