# Generated by Django 5.2.11 on 2026-03-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_merchant_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
